services:
  db:
    image: mysql:8.4
    container_name: db_jds_ok
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hamburgeria
    ports:
      - "127.0.0.1:3320:3306"
    volumes:
      - voldb_jds_ok:/var/lib/mysql
      - ./db/db.sql:/docker-entrypoint-initdb.d/01-db.sql:ro
    networks:
      - net_jds_ok
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-P", "3306", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s


  app:
    build: .
    container_name: app_jds_ok
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - net_jds_ok
    depends_on:
      db:
        condition: service_healthy

volumes:
  voldb_jds_ok:
    external: true
    name: jwt-database-sql-ok_voldb_jds_ok

networks:
  net_jds_ok: